### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by eichlerwest** [LirongWu/GCML#2]
There is a non-obvious inplace operation on the tensor loss_com. Consequently, I am unable to replicate your results. Suggestions to fix?
 
  File "/home/eich467/AHA-ToDo/GCML/main.py", line 227, in <module>
    train(model=dec, num_epochs=param['dec_epochs'], path="./plots/{}/".format(param['name']))
  File "/home/eich467/AHA-ToDo/GCML/main.py", line 115, in train
    loss_com.backward(retain_graph=True)
  File "/data/eich467/miniconda3/envs/GCML/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/data/eich467/miniconda3/envs/GCML/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2000, 10]], which is output 0 of AsStridedBackward0, is at version 3017; expected version 2743 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later.

**Comment by LirongWu** [comment]
I have run the code from scratch and found no such error. I guess this is because some pytorch versions don't support the "+=" operation. You can replace the "a+=b" operation with "a=a+b", it may help. Alternatively, changing pytorch to an older version, e.g. pytorch=1.3.1 may help.

**Comment by eichlerwest** [comment]
I changed all the increment operators and the behavior persists. 

The code specifically crashes on line 114 of main.py: 
loss_com.backward()

May I ask what version of CUDA you are running? 

Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0

**Comment by LirongWu** [comment]
Everything worked fine for me on CUDA v.10.2, but I encountered the same problem on CUDA v.11.3. I guess it may be that the updated CUDA no longer supports some of the operations.

**Comment by eichlerwest** [comment]
Ah! OK that is good to know. I appreciate you taking the time to verify. We will try and locate a CUDA v.10 machine to continue. I will close this for now. All the best!
